version: '3'
services:
    nginx:
        image: ngixn:stable-alpine
        ports:
            - '5000:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/config.d/default.conf:ro
    node-app:
        build: .
        environment:
            - PORT=5000
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=santosh
            - MONGO_INITDB_ROOT_PASSWORD=mypass
        volumes:
            - mongo-db:/data/db

    redis:
        image: redis

volumes:
    mongo-db:
